version: "3.9"
services:
  web:
    image: nginx:latest
    container_name: webhooks-websrv
    ports:
      - "${WEBHOOKS_PORT}:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/dev.webhooks.denhac.org.nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel_network

  app:
    build:
      context: ../
      dockerfile: dev_containers/Dockerfile
    volumes:
      # - ..:/var/www/html
      - ../storage:/var/www/html/storage
    develop:
      watch:
        - action: rebuild
          path: ../
          ignore:
            - dev_containers/*
            - storage/*
            - .git/*
        - action: rebuild
          path: dev_containers/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network

  ngrok:
    build:
      dockerfile: ./ngrok/Dockerfile
    environment:
      - WEBHOOKS_PORT=${WEBHOOKS_PORT}
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
    ports:
      - "4040:4040"
    depends_on:
      - web
    networks:
      - laravel_network

  db:
    image: mysql:latest
    container_name: webhooks-db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password="$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 0s
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=webhooks-db
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

  mock_denhac_dot_org:
    driver: bridge

volumes:
  db-data:
