#! /usr/bin/env bash
echo "Linking vendor packages from build..."
# cp -r /var/www/build/. .
rm -rf vendor
ln -s /var/www/build/vendor vendor

# echo "Installing packages..."
# composer install

echo "Preparing autoload..."
composer dump-autoload -o
if [ $? -ne 0 ]; then
  echo "Autoload failed!"
  exit $?
fi

echo "Running migrations..."
php artisan migrate
if [ $? -ne 0 ]; then
  echo "WARNING: Failed to run migrations! Continuing..."
fi

echo "Seeding database..."
php artisan db:seed

echo "Starting PHP"
php-fpm &

echo "Application ready."

mkdir -p storage/logs/
touch storage/logs/laravel.log
tail -fn 0 storage/logs/laravel.log
